### ISSUE TITLE
Web.Contents failed to get contents from

### ISSUE THREAD

**Issue by cavanell** [migueesc123/YoutubeAnalytics#10]
Hi there, 
Thanks for looking into this. I opened the template (having followed the directions of all the other video) and I'm receiving this error. I feel like I'm so close but so far away from making this work.

<img width="402" alt="youtubecapture" src="https://user-images.githubusercontent.com/38706251/39216787-e7d0a850-47d1-11e8-9b41-a5830b2d5347.PNG">

<img width="424" alt="youtubecapture2" src="https://user-images.githubusercontent.com/38706251/39216786-e7baa83e-47d1-11e8-80af-abfbfb744a35.PNG">

**Comment by migueesc123** [comment]
hey! 
Could you Edit the queries and remove that one to see if the rest of the queries work? or try previewing the rest of the queries to see if they work for you?

I've just tried using the template but couldn't replicate the issue. Would you mind creating a query from scratch just using the custom connector and not the template to see if the custom connector is working for you?

**Comment by cavanell** [comment]
I'll try that. 

Just using the custom connector gave me the following.

<img width="867" alt="capture" src="https://user-images.githubusercontent.com/38706251/39275479-40ec2a7c-489a-11e8-8dd4-e784cdc4354d.PNG">

**Comment by migueesc123** [comment]
Would you mind checking if the "Channel" query works for you? I think that the Videos query might not work if you don't have any videos under your authenticated primary channel.

**Comment by migueesc123** [comment]
Hey, I'm going to close this ticket, but if your situation wasn't resolved please let me know so we can open this again.
