### ISSUE TITLE
How do you make the click handler wait for the api to load?

### ISSUE THREAD

**Issue by BrentGrammer** [migueesc123/YoutubeAnalytics#11]
Hi, this may not be relevant to this project, but I posted a question on your youtube video and was instructed to post on the github page - I hope this is okay and my question is in the right area.  

I am trying to make a call to the youtube data API v3, and am finding that the click handler on my button to make the call can fire the handler making the call before the API client library is loaded.  How do you make the click handler wait (to function like a promise, for example) so that the call function will not fire until all necessary api components have finished loading.  Pics of my code are attached and a pic of the error that happens if the button is clicked before the API loads.  Thank you for any help.

**Index.html with button that makes the API Call:**

![indexhtml](https://user-images.githubusercontent.com/35240225/39656766-9885e648-4fbf-11e8-9a96-018eec428ce1.PNG)
**Scripts file loaded into index.html:**

![scripts](https://user-images.githubusercontent.com/35240225/39656771-a3b31874-4fbf-11e8-968c-1485ac0f2eb5.PNG)

**The error when btn is clicked too soon (shown in console in devtools):**

![asyncerror](https://user-images.githubusercontent.com/35240225/39656774-a7fc1bce-4fbf-11e8-8fe6-fecddbd88a58.PNG)
Just to be clear, the call and the button works, it's just that if it is clicked too soon, there will be an error - I want to make it so that when the button is clicked, even if it is too soon, the handler will wait for all of the API to load before it fires the call.  Thanks again.

**Comment by migueesc123** [comment]
Hey Brent!

I wish that I could help you, but I'm not familiar with Javascript. The code that I created used the M language from Microsoft's Power Query and some simple HTTPS requests. The video on YouTube was mainly created for the topics covered in this repo and to follow the step by step guide that I have on it.

I'd recommend that you try posting your question on the dedicated forums for the API or perhaps on Stackoverflow.

Sorry that I couldn't be of more help.

**Comment by BrentGrammer** [comment]
Ok, thank you for responding anyways.
-Brent
