### ISSUE TITLE
Authentication Issues with YouTube Custom Connector

### ISSUE THREAD

**Issue by khosny2018** [migueesc123/YoutubeAnalytics#14]
Hi followed your instructions and when i get to the Log on Screen to validate my credentials I get the following error message.  Any ideas on how to resolve this? 

![image](https://user-images.githubusercontent.com/42989365/45180947-9bd5b780-b1e2-11e8-9b22-c5d70c048317.png)

**Comment by migueesc123** [comment]
it seems to be related to your version of the [WebApp.json file](https://github.com/migueesc123/YoutubeAnalytics/blob/YoutubeAnalyticsConnector/YoutubeAnalytics/WebApp.json). You'll need to make sure that it's correctly set up and named in your custom connector.

**Comment by khosny2018** [comment]
Thanks for the tip.  Now, I am getting an issue with the redirect URL.  How do I know what that URL should be?

**Comment by migueesc123** [comment]
Please refer to the [step one of the documentation ](https://github.com/migueesc123/YoutubeAnalytics/blob/YoutubeAnalyticsConnector/README.md)on how to set up your WebApp and redirect url.

**Comment by khosny2018** [comment]
Thank you for your help.  It worked.
