### ISSUE TITLE
Is this now supported in Service?

### ISSUE THREAD

**Issue by pstevens33** [migueesc123/YoutubeAnalytics#15]
Hi Miguel,

Have you had any luck getting this to work in Power BI Service using either the Personal or Enterprise gateways? I didn't have any luck with the enterprise gateway as my connector was not showing up in the list of available data sources. I got further with the Personal gateway but I got this error when it asked me to update my credentials for the data source.

![image](https://user-images.githubusercontent.com/18253410/45591232-9292cc00-b901-11e8-8f7f-c15f448d4b86.png)

Please let me know if you have any tips.

Thanks,
Parker

**Comment by migueesc123** [comment]
hey! could you please download the latest version of the connector? it does have the code needed to work on the service

**Comment by pstevens33** [comment]
Thanks Miguel! I will download the latest version. Do you recommend the personal or enterprise gateway?

**Comment by migueesc123** [comment]
I think it only works with the personal gateway right now

**Comment by pstevens33** [comment]
Thanks Miguel!
