### ISSUE TITLE
Data Anonymization Issue

### ISSUE THREAD

**Issue by pstevens33** [migueesc123/YoutubeAnalytics#17]
Hi again Miguel,

Ever since the update to the Youtube Analytics API on September 17, 2018, I have not been receiving proper data regarding viewer demographics. This is not a problem with the connector because I receive the same problematic data when using the API Explorer. The following is an explanation of why the data is missing:

https://developers.google.com/youtube/analytics/data_model#data-anonymization

Basically, this excerpt states that if your channel does not meet the minimum traffic requirements, then you will probably be missing some data. Do you know of a potential work around to this issue? And have you seen this issue for your channel's data? I understand that your channel is bigger than mine so you might not be affected. For reference, my channel is www.youtube.com/c/bielite.

Thanks again for all of your work on this. I hope to hear from you soon.

-Parker

**Comment by migueesc123** [comment]
I'm actually facing some issues with the API as described on issue #16 

I wish that I could tell you a workaround, but I wouldn't know what query plan would work to make that happen. If you have the chance, head over to stackoverflow to see what people are saying about this topic - they might have a certain workaround that you could later use with the GetReports function

**Comment by pstevens33** [comment]
Thanks for the response. I haven't found any questions pertaining to this on SO given that it's a fairly new update. Thinking more about it, I'm not sure if there will be a workaround given that YouTube is explicitly trying to hide small data traffic. Just to clarify, here is a small snippet of the issue I'm facing when invoking the Video Stats function:

![image](https://user-images.githubusercontent.com/18253410/46563444-680bb180-c8b6-11e8-8ed0-2d660ddd5a9a.png)

You can see that there was an adImpression, meaning there was a view. However, this view doesn't show up because it was the only view for that video/country/day combination. If possible, could you or anyone let me know if you are running into the same issue? I imagine this affects many others.

Thanks again.

**Comment by migueesc123** [comment]
Hey,

Check out this specific [reply](https://github.com/migueesc123/YoutubeAnalytics/issues/16#issuecomment-425689918)

**Comment by pstevens33** [comment]
Gotcha, I had read through the thread but wanted to give my two cents that it isn't a bug. Instead it is the direct result of this [update](https://developers.google.com/youtube/analytics/revision_history). Maybe you already knew this and I'm misunderstanding the other thread. My thinking is that Video Stats will no longer work as expected for anyone because you will show 0 views for every line that does not meet a minimum (un-announced) traffic threshold. Personally, I am only meeting this threshold for United States and India traffic so I will not see data for hits from any other country.

Hope this all makes sense. Thanks sir.
