### ISSUE TITLE
Urgent | PowerBI | Youtube Analytics - Custom Connector 

### ISSUE THREAD

**Issue by surajprao** [migueesc123/YoutubeAnalytics#18]
![image](https://user-images.githubusercontent.com/45458600/49224487-8f3eb500-f407-11e8-8840-6d76367b6ece.png)

I have gone through all the videos, created Google API gave all the access required and the youtube videos are also in the same ID as where the Google APIs is created. I can see all the videos listed in query but there seems to be some error. (want to use the power bi template shared)

I tried to change the code by adding end date modification mentioned in one of the thread also. Couldnt get through. I have reached a dead end. I dont have much time so would like some urgent supprt from this amazing community.

**Comment by steffels** [comment]
I am also now having issues with the connector. It was working as recently as Tuesday, but on Wednesday I started getting errors. Here is a screenshot of my error:

![ytanalyticserror](https://user-images.githubusercontent.com/45468340/49250364-a45a1a80-f3ec-11e8-89d2-60cb1f6e42ae.png)

The Channel and Video queries work with no problems, it's just the ones using the "GET Reports" function that cause errors. In the URL that has an error there is a v1, could this have to do with needing to upgrade to v2?

Thanks!

**Comment by migueesc123** [comment]
Hey @steffels ! did you download the .mez from this repo? or did you download the project and compiled the project on your own?
I updated the code a few months ago. It turns out that I updated the full source code and it's available on this repo, but the older .mez file still had the v1 method in it. I'll upload a new version of the .mez file for it

**Comment by steffels** [comment]
I copied the .mez, and your fix worked! Thank you for the quick response!
