### ISSUE TITLE
Multichannel support

### ISSUE THREAD

**Issue by scofeeeld** [migueesc123/YoutubeAnalytics#19]
Hi Miguel!
I have a question and need your help.
How can I use or change your connector to ensure a possibility of using it for multi channel (the case if I have more than one channel on one e-mail)

**Comment by migueesc123** [comment]
hey! 

I haven't fully delved into it, but you could potentially customize the connector to accept multiple "channel ids" and, if the user has access to those channels, then it could retrieve the data for those channels.

Right now the connector works by simply accessing the primary channel of the authenticated user (probably the best UX for a single user).

**Comment by scofeeeld** [comment]
Hey!
I understand.
But could you help me please in one more case.
How should I edit your connector to make additional field in Query editor in PBI Desktop in which I'll be able to fill id of a channel directly?

It is very important for me. I think it's very easy for you.
Thank you very much and have a nice day

**Comment by migueesc123** [comment]
Hey Evan,

There are no current plans to implement that type of behavior for this Custom Connector. Based on the license that this repo has, you can definitely use the code and customize it to your needs. 

In the event that this is an urgent matter to you, we could allocate some time under a consultancy work. Please contact me via email to miguel@poweredsolutions.co if you're interested.

I'm currently focusing on paid consultancy work around Custom Connectors for the next few months and will only be revisiting this connector for bugs or for big changes (like the one you brought up on the v1 to v2 situation)
