### ISSUE TITLE
Connector appears to be missing statistics including views, likes and comments

### ISSUE THREAD

**Issue by thunder247** [migueesc123/YoutubeAnalytics#20]
Hey, I've got the connector working and am excited about the potential.  However, I appear to be experiencing issues with respect to the data being loaded.

I have 279 videos and started my channel in August 2016.

The connector is under-reporting the views, likes, shares, comments, etc. for any video I've manually checked, including the "What if Ryan Reynolds did Christmas Carpool Karaoke".  I've attached a screenshot of what I see in Power BI and what I get directly from YouTube Analytics.

BTW.  I definitely DON'T have any filters set in Power BI!

Thanks!
![view count](https://user-images.githubusercontent.com/46189068/50475053-34bf5700-09bb-11e9-8edb-a8b43ffd4d28.jpg)
[20181227 YouTube Analytics Watch Time Report.xlsx](https://github.com/migueesc123/YoutubeAnalytics/files/2712070/20181227.YouTube.Analytics.Watch.Time.Report.xlsx)

**Comment by Lestatgaming** [comment]
Just to confirm this issue, I have the same problem.
![youtube stats](https://user-images.githubusercontent.com/46198914/50488609-49234400-09fb-11e9-930c-28d9f0cf606f.png)
![pbi stats](https://user-images.githubusercontent.com/46198914/50488610-49234400-09fb-11e9-87be-8762d28a30e1.png)

**Comment by migueesc123** [comment]
Hey!

The YouTube team deployed a change a few months ago that is causing the API to not provide all of the data unless it meets certain tresholds.
You can read about it from this issue #17 and the official documentation from YouTube [here](https://developers.google.com/youtube/analytics/data_model#data-anonymization).

You could still use the other functions to get the global views of a video, but having the breakdown by country will rely on your video meeting those criterias / tresholds.

There's nothing that I could possibly do on the connector side to create a workaround - this is a limitation of the API itself.

**Comment by thunder247** [comment]
Thanks Miguel.  Another disappointing decision from YouTube.  :-(
