### ISSUE TITLE
Autentification

### ISSUE THREAD

**Issue by vevilarinho** [migueesc123/YoutubeAnalytics#21]
Hi, 
First of all, thanks for sharing this 👍 
Well, I'm having this error "redirect_uris" not founded, when I tried to connect the data in power bi(after all the steps).
Any ideia of what i most be doing wrong?

Forget, already workin well!

**Comment by migueesc123** [comment]
Hey! I see that you closed this issue. Do you still need help? the error is caused when your API App doesn't have the redirect uri set up correctly.

**Comment by vevilarinho** [comment]
Yes, no need help anymore, I discovered where the error was (the json file from google). Works fine now. Thank you again!
