### ISSUE TITLE
[Expression.Error] We couldn't find the file 'WebApp.json'

### ISSUE THREAD

**Issue by MoskvaCho** [migueesc123/YoutubeAnalytics#24]
Dear migueesc123,

First of all, thanks for your guide on Custom Connectors for Youtube API.
It was clear and straightforward to follow, even for a beginner like me.

However, I have encountered some problems with regards to loading the Custom Connector.

Issues:
1. Opened Power BI -> Get Data -> Other -> YoutubeAnalytics.Navigation (Beta)
No Icon present, and name is different from your tutorial.

2. [Expression.Error] We couldn't find the file 'WebApp.json'
When I try to connect to the Custom Connector (with modified json w/ credentials)
Power BI claims that it cannot locate WebApp.json

Differences:
Due to different versions & changes with updates, these are some steps that I have taken
that is unspecified in your tutorial

1. Google API -> Credentials -> OAuth Consent Screen
Had to add "powerbi.com" under authorized domain, in order to add 'Authorized Redirect URI'
(https://oauth.powerbi.com/views/oauthredirect.html)

Thanks again, Will be waiting for your response!

**Comment by migueesc123** [comment]
Hey!
Thanks for reporting this. It's hard to keep up with the changes, but its nice knowing that they are easy to spot and get through even for beginners.

At this current time, I'm unable to commit to updating the documentation of setting up the WebApp. I wish that I was able to make that happen, but I'd much rather send you to the current official documentation that Google / YouTube has around this so you can always have the latest and the greatest. The important aspects from this connector are the redirect ui and the webapp.json that you can export once your webapp is ready. Once those are good to go, everything is handled inside the actual Custom Connector where I have the full control of how things go.

If you happen to have time and would like to contribute to this repo, you're more than welcome to!

**Comment by ImkeF** [comment]
Hi @MoskvaCho ,
you'll get the error message "We couldn't find the file 'WebApp.json'" when you zip the folder instead of the single files. So make sure to go one step deeper into the folder, check all files and then zip them.

**Comment by K37V1N** [comment]
@ImkeF This helped with with a different project in Github that I was having trouble with, thanks!
