### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by israeldavid** [migueesc123/YoutubeAnalytics#25]
After read, research about the new way activate the custom connector, finally i could activate the custom connector but give a error when i try to validate the account, google show a error the javascript. So what i can do,

**Comment by migueesc123** [comment]
hey, could you share the javascript error that you're receiving? a screenshot if possible

**Comment by israeldavid** [comment]
Hi, thanks for answer, today i delete the proyect api, and create a new one, but now this shows me.

[http://www.quehacedavid.com/wp-content/uploads/2019/07/error.jpg](url)

**Comment by migueesc123** [comment]
it could be that you deleted the wrong app? you need to verify what data  you're using inside your webapp.json file and if it's using the correct values or not for the app that you have available

**Comment by israeldavid** [comment]
After review the file, and directories, i have to delete the instalation the power bi and install the software again, and works but, show me this error: [http://www.quehacedavid.com/wp-content/uploads/2019/07/errorYoutube.jpg](url)

**Comment by israeldavid** [comment]
all right works fine.
