### ISSUE TITLE
some error in query

### ISSUE THREAD

**Issue by raising01** [migueesc123/YoutubeAnalytics#26]
when I have done the mez file, and put it in right place.
I open Youtube Analytics Template.pbit, it show the error message like the attach pic.
How to solve it? please

<img width="960" alt="apply qurey change" src="https://user-images.githubusercontent.com/46309751/62516401-93a15480-b857-11e9-944d-6278796d1652.png">

<img width="960" alt="query error1" src="https://user-images.githubusercontent.com/46309751/62516509-df53fe00-b857-11e9-87ee-724f4035624d.png">

<img width="960" alt="query error2" src="https://user-images.githubusercontent.com/46309751/62516530-f0047400-b857-11e9-9ee0-b4de5e660c71.png">

**Comment by migueesc123** [comment]
Hey!
It could be for a number of reasons, but this is an error that you get by not having the correct authentication to the access that you're trying to get.
Here's a few previous issue that had a similar situation:
#22 
#7
