### ISSUE TITLE
Problem with Redirect URI

### ISSUE THREAD

**Issue by Billy19990923** [migueesc123/YoutubeAnalytics#27]
Creating my first Google API Project - Connecting to the Youtube API(https://www.youtube.com/watch?v=6r8hrDHUv6s)

i have an issue when i have to enter the URI in the creation of credentials step. The error message i receive is "Invalid Redirect: domain must be added to the authorized domains list before submitting.
![2019-08-24 075111](https://user-images.githubusercontent.com/54458842/63629401-74bb0480-c644-11e9-8fc1-c6b7f728ca51.jpg)

**Comment by migueesc123** [comment]
Hey! I see you closed this ticket and I’m guessing that you were able to resolve this situation. You have to click on the link for “authorized domains list” and add the domains in there first. They added that step just a few months back after I created the video
