### ISSUE TITLE
Some API calls return errors

### ISSUE THREAD

**Issue by mattzipan** [migueesc123/YoutubeAnalytics#28]
Hi, after following all instructions, some API calls return errors when using the template file:
https://i.imgur.com/ruBhWBA.png
https://i.imgur.com/Bk1qhrq.png
https://i.imgur.com/3q1T7tP.png
https://i.imgur.com/yeQdCuj.png

Do you have any idea with what this could be related?

**Comment by migueesc123** [comment]
Hey! Thank you for reporting this. I haven’t taken the time at looking at the template In a long time.
Some of the errors that I see could be related to your YouTube channel not having the revenue field available, but others do some to look like queries that simply no longer work.

I’ll take a look at it during the weekend and thank you for reporting this!

**Comment by migueesc123** [comment]
Hey!
Not sure why I never updated this, but I updated the code 6 months ago and it should be working.
