### ISSUE TITLE
Forbidden access error

### ISSUE THREAD

**Issue by EnriqueProinfo** [migueesc123/YoutubeAnalytics#29]
Hello:

I have setup you connector with success, but can only access to Channel and Countries tables, and in preview I can see videos data, but when I push de Load Data Button I get a "Forbidden access" error.

Any clue?

Thanks in advance!
![Preview](https://user-images.githubusercontent.com/3330205/66550177-1e971780-eb45-11e9-899c-a28878df46b6.PNG)
![Forbidden](https://user-images.githubusercontent.com/3330205/66550185-222a9e80-eb45-11e9-83fb-92ea1d939b9f.PNG)

**Comment by migueesc123** [comment]
Hola Enrique!

Realmente no sabría decirte. ¿Podrías intentarlo desde otra computadora? Realmente no deberías de obtener ese error para los vídeos.

Puedes revisar el código que hace esta llamada [acá](https://github.com/migueesc123/YoutubeAnalytics/blob/ebc12360113f9d1738fc6b3172b004f8cb88ff1b/YoutubeAnalytics/YoutubeAnalytics.pq#L443)

**Comment by sachintholia** [comment]
i am facing the same issue, but i am not getting videos only 

 i think problem may lie in one of the following and need help in following, 


1.  Google has introduced Oauth Scope, I gave youtube analytics read only scopes  which does not require app verification.... it does not work , then i tried creating an internal orgranisation app which does not require any verification , but it also does not work as it can work internally

2. youtube account owner vs manager might be a issue 

but not getting the data loaded, tried all permutation and combination for oauth

**Comment by migueesc123** [comment]
hey! the custom connector* only has the scope for the owner and not the content manager, so this means that only the "owner" of the channel will be identified correctly.
Nevertheless, if you do see something in the preview window then it means that it actually got some results from the API.

**Comment by sachintholia** [comment]
Thanks for quick response. Still I am not able to get the data in preview too.
![image](https://user-images.githubusercontent.com/7420015/66731172-9336c280-ee73-11e9-8293-7eeef5e17934.png) 

I think there is some change in getting credential with is not discussed in help file 

When i create a credential at global level , both youtube analytics, and youtube data v3 api were enabled  , i also enabled youtube reporting api  and created the json file 
![image](https://user-images.githubusercontent.com/7420015/66731276-27a12500-ee74-11e9-93fd-37c30863f303.png)



In Oauth Concent screen tabl , 

I was asked to add authorised domain powerbi.com without which redirect url can not be entered , so i did that 

Also it ask for scope , if i do not include scope , i get the above forbidden access error but if i add youtube data and analytics scopes , it ask for submit app for verification  which is no where discussed in video created for telling how to get oauth . Need your support , 
Request you to create a new credential for yourself , to see this issue . Old oauth file may still be working for you 

![image](https://user-images.githubusercontent.com/7420015/66731397-d3e30b80-ee74-11e9-97d5-00579d858963.png)

I am not able to use this , please suggest how can i get the data , Yes i am the primary owner of the channel , doing from same email id

**Comment by sachintholia** [comment]
i have tried oauth redirect url as https://oauth.powerbi.com/views/oauthredirect.html as well as old one which is shown in screen shot in preview message 

I also noticed one thing while entering the credentials in power bi 
When i sign in i get this error 
![image](https://user-images.githubusercontent.com/7420015/66731987-b6fc0780-ee77-11e9-954d-3b2210b4c7bc.png)

on clicking yes  then again 
![image](https://user-images.githubusercontent.com/7420015/66732015-d2671280-ee77-11e9-8fad-4c699c07789a.png)
AFter that i am taken to sign in page, 


this might also cause the error , I am not technical , so writing my issue in very vauge way , please support

**Comment by migueesc123** [comment]
@sachintholia what you might be facing sounds different from what @EnriqueProinfo is facing given that @EnriqueProinfo  can see the data in the preview window of the videos.

I'm going to create a new issue specific to your case @sachintholia  so we can talk about it

**Comment by migueesc123** [comment]
Hey @EnriqueProinfo !
I'm going to close this ticket, but if you require further assistance, just let me know.
