### ISSUE TITLE
Audience retention

### ISSUE THREAD

**Issue by guyinacube** [migueesc123/YoutubeAnalytics#3]
Audience retention would be a great stat to include with this.

**Comment by migueesc123** [comment]
Here's a list of all the video metrics that the connector currently has under the YoutubeAnalytics.VideoStats function:
views 
likes 
dislikes 
shares 
estimatedRevenue 
comments 
averageViewDuration 
estimatedMinutesWatched 
adImpressions 
cpm 
averageViewPercentage 
subscribersGained 
subscribersLost 
audienceWatchRatio

the dimensions used are:
Country
VideoID
Day
(adding any other dimension could potentially put some YouTube channels over the requests/sec limit that the free API has)

The ones related to audience retention are:
audienceWatchRatio
averageViewPercentage 

You could also consider the following ones as retention ones:
averageViewDuration 
estimatedMinutesWatched 

There's another metric that is missing:
relativeRetentionPerformance 

But that metrics does not work with the dimensions previously listed. It only work with:
elapsedVideoTimeRatio
and then you can use some filters like VideoID plus start and end date but that's it. Do you think that with the current metrics that we have is enough? or do you see a huge potential in those 2 missing ones?

*****(edit) only 1 metric missing

**Comment by migueesc123** [comment]
Hey Adam!

Let me know if the metrics available are good enough or if you're looking for something else in particular.

**Comment by migueesc123** [comment]
Hey @guyinacube ! 

Just added a few new functions that work similar to how the MailChimp.Instance work for the MailChimp connector. You can create your own query against both the YouTube Data API v3 (through the GETPublicData function) and the YouTube Analytics API (through the YoutubeAnalytics.GETReports), which means that you could query any data that you want for things like audienceretention, agegroup, gender and even more.

Let me know your thoughts!
