### ISSUE TITLE
Issue connecting to data

### ISSUE THREAD

**Issue by migueesc123** [migueesc123/YoutubeAnalytics#30]
Thanks for quick response. Still I am not able to get the data in preview too.
![image](https://user-images.githubusercontent.com/7420015/66731172-9336c280-ee73-11e9-8293-7eeef5e17934.png) 

I think there is some change in getting credential with is not discussed in help file 

When i create a credential at global level , both youtube analytics, and youtube data v3 api were enabled  , i also enabled youtube reporting api  and created the json file 
![image](https://user-images.githubusercontent.com/7420015/66731276-27a12500-ee74-11e9-93fd-37c30863f303.png)

In Oauth Concent screen tabl , 

I was asked to add authorised domain powerbi.com without which redirect url can not be entered , so i did that 

Also it ask for scope , if i do not include scope , i get the above forbidden access error but if i add youtube data and analytics scopes , it ask for submit app for verification  which is no where discussed in video created for telling how to get oauth . Need your support , 
Request you to create a new credential for yourself , to see this issue . Old oauth file may still be working for you 

![image](https://user-images.githubusercontent.com/7420015/66731397-d3e30b80-ee74-11e9-97d5-00579d858963.png)

I am not able to use this , please suggest how can i get the data , Yes i am the primary owner of the channel , doing from same email id

_Originally posted by @sachintholia in https://github.com/migueesc123/YoutubeAnalytics/issues/29#issuecomment-541510903_

**Comment by migueesc123** [comment]
Hey 
Unfortunately, the YouTube team has changed some of the steps of my original video that I created back in 2017. 
The scopes have always been required and you can check the code of the custom connector that mentions the scopes being required:
https://github.com/migueesc123/YoutubeAnalytics/blob/YoutubeAnalyticsConnector/YoutubeAnalytics/YoutubeAnalytics.pq#L27

I've added some notes on the scopes that are needed on the readme file of this repo. Let me know if by adding those scopes to your apps the connector works for you.

**Comment by sachintholia** [comment]
"yt-analytics-monetary.readonly", 
"yt-analytics.readonly",  
"youtube.readonly"

i have been trying the scopes but some of them are sensetive scopes as per google, so if application is private requires verification  or application need to be for internal organisation , 
![image](https://user-images.githubusercontent.com/7420015/66791070-3f2deb80-ef10-11e9-8d28-82d7b8c44773.png)




i choose for internal organisation and migrated the app to organisational app but then power bi did not connect  while signing in power bi and getting channel authentication 

![image](https://user-images.githubusercontent.com/7420015/66791172-b4012580-ef10-11e9-8005-1206742c5d8a.png)

**Comment by migueesc123** [comment]
I wish that I could tell you more about this, but I'm not closely familiar with the new app experiences from Google.
Here's how my app looks like:
![image](https://user-images.githubusercontent.com/9544580/66851955-90a29e80-ef41-11e9-9d5e-f609fd63e5c7.png)

I'd also recommend that you get in touch with the Google API team or the support forums so you can get assistance on how to set the application correctly based on the new guidelines and your requirements. Share your findings with us.

In regards to the Custom Connector, it uses those scopes mentioned before and it uses the YouTube Analytics API v2 and the YouTube Data API v3.

**Comment by sachintholia** [comment]
Finding no clue, I have tried my three four accounts of google, and on all this is the problem. Need support

**Comment by migueesc123** [comment]
Hey!

This GitHub repo is primarily for support of the custom connector, where one of the requirements for this connector to work is to have the application correctly set up.
While I wish that I could tell you exactly what’s happening, it requires a deep dive into your specific case and set up to see what’s going on and what might be needed for your application to be set up correctly.

I’d recommend that you get in touch with a developer with experience with the Google Apps in order to correctly set up your account, and you can also contact me via email:
Info@poweredsolutions.co
To request for our paid services implementing this application and or custom connector requirements for you.
I’ll be closing this ticket, but if you ever have issues with the custom connector, please let us know.
