### ISSUE TITLE
Brand Account

### ISSUE THREAD

**Issue by sachintholia** [migueesc123/YoutubeAnalytics#31]
As Google have made a mandate to review the app for sensitive scope , i try to make an internal app and I was able to get the data. Issue is I am able to get the data only of the channel linked to my account but not of channel of my brand account. I am primary owner of brand account and brand account was created with same email id, still not able to get the data. 

Has any one able to get the data from channel linked to email as well as from brand account using the internal app option of google oauth2 api

**Comment by migueesc123** [comment]
Hey!
Glad you were able to make the set up the app!

Thanks for the feedback on enabling the connector to accept this type of scenario where you have a brand account and would like to access any channels under that brand account.

The current configuration of the custom connector makes every call based on the authenticated account and the main channel under the authenticated account. 
You can see an example of the call that the connector uses in the following line of the code:
https://github.com/migueesc123/YoutubeAnalytics/blob/fc2ee468a16274d806e4c810f6b155276d1a72dd/YoutubeAnalytics/YoutubeAnalytics.pq#L446

Specifically where it says "forMine=true".

There are no plans to add any new features to this custom connector, but you can change the code of the Custom Connector as you please following the connector's license:
https://github.com/migueesc123/YoutubeAnalytics/blob/YoutubeAnalyticsConnector/LICENSE

If you'd like to inquire about my services to customize this or any other connector to your specific needs, you can also contact me via email to info@poweredsolutions.co 

Thanks again for your feedback!
