### ISSUE TITLE
Can't get data when using dimensions and metrics containing underscore

### ISSUE THREAD

**Issue by SMR-89** [migueesc123/YoutubeAnalytics#32]
Hello,

I am getting an error when I try to retrieve data using the function #"GET Reports".

For example, I've been able to get a report using this query:
`= #"GET Reports"(#date(2018, 1, 1), #date(2019, 12, 2), "views,likes,dislikes,comments,shares", null, "day", null, null, null, null)`

However, when I try to use any of the metrics or dimensions containing underscores, I get a 400 Bad Request error.

For example, I can't get the watch time minutes by day using the following query:

`= #"GET Reports"(#date(2018, 1, 1), #date(2019, 12, 2), "views,likes,dislikes,comments,shares, watch_time_minutes", null, "day", null, null, null, null)`

The error message is:

> DataSource.Error: Web.Contents no pudo obtener el contenido de 'https://youtubeanalytics.googleapis.com/v2/reports/?ids=channel%3D%3DUCJsDSIpAvTN-_IArn2IyYlA&startDate=2018-01-01&endDate=2019-12-02&metrics=views%2Clikes%2Cdislikes%2Ccomments%2Cshares%2Cwatch_time_minutes&dimensions=day' (400): Bad Request.
Detalles:
    DataSourceKind=YoutubeAnalytics
    DataSourcePath=YoutubeAnalytics
    Url=https://youtubeanalytics.googleapis.com/v2/reports/?ids=channel%3D%3DUCJsDSIpAvTN-_IArn2IyYlA&startDate=2018-01-01&endDate=2019-12-02&metrics=views%2Clikes%2Cdislikes%2Ccomments%2Cshares%2Cwatch_time_minutes&dimensions=day

The same error is obtained for any of the following metrics: 
- annotation_click_through_rate
- annotation_close_rate
- average_view_duration_seconds
- estimated_partner_revenue
- subscribers_gained
- subscribers_lost
- views_percentage
- watch_time_minutes

Is it an issue? Or am I doing something wrong?

Thank you.

**Comment by migueesc123** [comment]
I think that you're using the names of the reporting API and not the Analytics API.
![image](https://user-images.githubusercontent.com/9544580/69989855-8b5ddb00-1512-11ea-8650-176f6b9a02fd.png)
For example, this should work:
![image](https://user-images.githubusercontent.com/9544580/69990012-ded02900-1512-11ea-81e1-6fec27b50146.png)

`= YoutubeAnalytics.GETReports (
             #date(2018,1,1), 
             #date(2019,12,2), 
             "views,likes,dislikes,comments,shares,annotationClickThroughRate,annotationCloseRate,averageViewDuration", 
             "USD", 
             null, 
             null, 
             null, 
             null, 
             null)`

Hope this helps!
