### ISSUE TITLE
Login/ Verify Google: "Try using a different browser."

### ISSUE THREAD

**Issue by ghost** [migueesc123/YoutubeAnalytics#34]
Hi,

I am going insane with the OAuth stuff.  I've been using this Power Bi connector for YouTube analytics. It was working just fine the last time I tried it in February. Now I wanted to use it again and make full use of it, just to find out that Google changed something and I am not sure how to fix that issue.

Now every time I try to log in and verify my Google Account IN POWERBI it keeps giving me the following message:

"You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser."

Maybe it has something to do with the change of Google's oauth process, maybe not. 
But since I am a noob with these things I need help on how to fix it.

yt-analytics-monetary.readonly
yt-analytics.readonly
youtube.readonly

I've added these. However, there are several yellow warning signs, just like on the screenshot you've added to issue #30 

I am not sure if it's related or not but I have zero idea how to get it working, maybe someone in here has it.

**Comment by ghost** [comment]
I've just tried the same connector on my freshly installed Power Bi on my second PC, same error message. So it has to be the settings and/or the connector.

**Comment by migueesc123** [comment]
could you share some screenshots of what you're seeing? Unfortunately there's nothing that I can do to change the OAuth 2.0 process as it is being dictated by Google and not the custom connnector

**Comment by ghost** [comment]
There you go. I'm not understanding the publishing part as I want to use it only for myself.
The channel is a brand account, but that didn't matter back in February. It was able to pull all needed data.
Also, there used to be an account manager selected in March that I just deleted, if that might be an issue?

Could it have something to do with the quota? I don't remember if I opened up your spreadsheet template and tried to pull tons of data - either way, I get this error

![Error1](https://user-images.githubusercontent.com/58746651/70560771-7aa00b80-1b89-11ea-9253-d1694398799b.jpg)
![error2](https://user-images.githubusercontent.com/58746651/70560773-7b38a200-1b89-11ea-9b2b-e3e9383d8e69.jpg)

**Comment by migueesc123** [comment]
it appears to be something implemented by google which I have no control over.
More info about it found here:
https://support.google.com/accounts/thread/14666711?hl=en

I'd highly recommend that you try this on a different computer to check if you're still getting the same issues on that one. I'm not able to replicate with my app which is not verified.
One thing about unverified apps is that you can use them, but you'll get a message like this one:
![image](https://user-images.githubusercontent.com/9544580/70564892-fafd4700-1b5e-11ea-90e0-5302123e3cdd.png)
but you can get past it by clicking on the link at the bottom.

**Comment by ghost** [comment]
I do understand that - the problem is, that I am not even getting that far. Instead of an error or anything, I've received the error I've displayed. For people that might have the same issue, I just recreated the credentials, now I receive a slightly different text:

![error3](https://user-images.githubusercontent.com/58746651/70565358-3c5b1a00-1b92-11ea-9d8a-e807e459b3e3.png)

**Comment by ghost** [comment]
Hi Miguel, it seems it was the managed account that caused problems. However, now I am getting a comparable error that you showed above. However, it's without a link that I can click to use it anyway. Any idea? 
![Erro4](https://user-images.githubusercontent.com/58746651/70810119-7a8b5000-1dc3-11ea-8b96-03a083b0a923.png)

**Comment by migueesc123** [comment]
I wish that I could give you any suggestions, but this is also new to me. What I can confirm is that the OAuth 2 flow is followed to the letter on this custom connector, so this is explicitly related to your app or something new that Google has done that I’m simply not aware of.

If you find anything, please let me know!

**Comment by migueesc123** [comment]
I wish that I could give you any suggestions, but this is also new to me. What I can confirm is that the OAuth 2 flow is followed to the letter on this custom connector, so this is explicitly related to your app or something new that Google has done that I’m simply not aware of.

If you find anything, please let me know!
