### ISSUE TITLE
Problem with connector

### ISSUE THREAD

**Issue by Bogomolov94** [migueesc123/YoutubeAnalytics#36]
![image](https://user-images.githubusercontent.com/60003021/75244319-a8860b00-57dc-11ea-9ef4-b4b91dd205dc.png)

Hi, Miguel! I write with a problem (look screenshot). Connector always works well. Before today...
Error message in English - "Cannot apply access to fields in type Null"
In mentioned  table (Table: Статистика (Youtube)) there are no "null" values at all. 
Can you help me?
Thanks

**Comment by migueesc123** [comment]
Hey!
Are you getting the same error when trying to refresh from the Power BI Desktop? if yes, please share the code of the query that is causing the error.

**Comment by Bogomolov94** [comment]
Hi again!
Yes. The same error was received in desktop version. Interesting thing... I checked query step by step and it worked (even when I tried to refresh preview). But then I clicked on "close and apply" and PBI showed me the same error.

This is the code of query related to table Статистика (Youtube)) 

let
    Source = #"Video Stats"(#date(2018, 1, 1), #date(2020, 03, 31), true, false),
    #"Renamed Columns" = Table.RenameColumns(Источник,{{"views", "Просмотры итого"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"averageViewPercentage", Percentage.Type}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "Custom", each [averageViewPercentage]/100),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Custom", Percentage.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"Custom", "% удержания"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"% удержания", Percentage.Type}, {"subscribersLost", type number}, {"subscribersGained", type number}, {"averageViewPercentage", Percentage.Type}, {"estimatedMinutesWatched", type number}, {"averageViewDuration", type number}, {"comments", Int64.Type}, {"shares", Int64.Type}, {"dislikes", Int64.Type}, {"likes", Int64.Type}, {"Просмотры итого", Int64.Type}, {"cpm", type number}, {"adImpressions", type number}, {"estimatedRevenue", type number}, {"video", type text}, {"day", type date}}),
    #"Sorted Rows" = Table.Sort(#"Removed Blank Rows",{{"day", Order.Descending}})
in
    #"Sorted Rows"

p.s. I write to you from Belarus, Minsk. We have time zone difference (8 hours). So I`m sorry for late answer.. :)

**Comment by migueesc123** [comment]
Thanks for reporting!
I'll try to take a look at this during the next couple of weeks and will update this issue accordingly.

**Comment by Bogomolov94** [comment]
Thanks a lot.
I will wait with impatience...)
Hope, that this bug was only an exception.

Have a nice day!

**Comment by Bogomolov94** [comment]
Miguel, hi again!
I have news..
In PQ I filtered metioned table (Статистика (Youtube)) by columns day, video. Filter <> null.
And It works now..
It strange..really
Because I didn`t see any null values at all.

nevertheless I ask you to check this bug..if you can.
I`m afraid that it will happen in future.

So I do not close issue. Just inform you about changes in situation. Probably it`s not neccessary to make global changes.
Still wait for your answer...

Have a nice day!

**Comment by nemessj** [comment]
Dear Miguel,
Great many thanks for this connector! I managed to make it work and connect to our YouTube channel, I saw the data, all fine. Then I refreshed and the connection seems to have broken. Even is I try with a new file it doesn't work. I get the error message "Expression.Error: Access to the resource is forbidden."
Any idea what went wrong? Many thanks for your feedback in advance!
![Source_access](https://user-images.githubusercontent.com/61737696/75780114-1a210480-5d5b-11ea-8add-c701b12192c4.png)

**Comment by Bogomolov94** [comment]
Miguel, hi!

Did you see what the problem was?

Now I have no such problem with connector. But who knows?...
It can return :)

**Comment by migueesc123** [comment]
I haven’t been able to reproduce. I’ve tried in the spare time that I have, but without any success. If you ever find a way to reproduce this issue on a new install, please let me know

**Comment by Bogomolov94** [comment]
Ok :) 
Thank you!
