### ISSUE TITLE
File not saved as .mez

### ISSUE THREAD

**Issue by Alaa21** [migueesc123/YoutubeAnalytics#38]
Hello

First thank you so much for your videos. 
In the step where you paste the Youtube connector in the custom connectors document. I don't have this folder in my documents and I also don't have it in program file. 
This is my power bi directory: C:\Program Files\Microsoft Power BI Desktop\bin
and in the bin document I don't have custom folder. I pasted the Youtube connecter in the bin file but it didnt' appear in power bi.

**Comment by fabiofrancoso** [comment]
You need to create the Microsoft Power BI Desktop folder in your user's documents folder and the Custom Connectors folder inside. After that paste the connector into that folder

**Comment by Alaa21** [comment]
> You need to create the Microsoft Power BI Desktop folder in your user's documents folder and the Custom Connectors folder inside. After that paste the connector into that folder

I tried that and didn't work :/ I don't see the connector in power bi

**Comment by Alaa21** [comment]
I think the issue is when I save the zip file as a .mez it still looks like a zip file for some reason 
when I click on file's properties I see that the file type is (Compressed (zipped) Folder (.zip))

**Comment by Alaa21** [comment]
Finally, issue solved 👯 I had to go to the folder press on **view** in the top and check the box (file name extensions )
