### ISSUE TITLE
"Expression.Error: Access to the resource is forbidden."

### ISSUE THREAD

**Issue by nanpuhaha** [migueesc123/YoutubeAnalytics#39]
Error occurred on this connectors for 'Videos' and 'Channel'.

> Expression.Error: Access to the resource is forbidden.

![2020-06-02 16;59;26 001](https://user-images.githubusercontent.com/9074297/83496169-aaeeb400-a4f3-11ea-91b9-4d54be4a4ec9.jpg)
![2020-06-02 17;00;07 001](https://user-images.githubusercontent.com/9074297/83496182-afb36800-a4f3-11ea-85bb-cb6cdb7ce9d9.jpg)
![2020-06-02 17;00;22 001](https://user-images.githubusercontent.com/9074297/83496188-b17d2b80-a4f3-11ea-878e-d3c46e61b7cf.jpg)
![2020-06-02 17;00;27 001](https://user-images.githubusercontent.com/9074297/83496190-b2ae5880-a4f3-11ea-8fbd-dab03e4893d2.jpg)

**Comment by migueesc123** [comment]
Hey!
This appears to be an issue with the authentication or at the WebApp level. I'd highly recommend that you try and debug your own calls to the REST API to see what type of errors you're getting from the API.
This isn't something that I can manage at the custom connector level, so you'll need to make sure that everything is setup correctly at your webapp level and that the authenticated user has all the right levels of access to get the info from their own account.

Should you require further support debugging the issue at your Webapp level, you can get in touch with us for paid support by emailing us at info@poweredsolutions.co 

Best!
