### ISSUE TITLE
impossible to connect

### ISSUE THREAD

**Issue by noliverte** [migueesc123/YoutubeAnalytics#40]
Hello,

I follow 3 first steps to get youtube data Analytics, but I can't connect after choosing (in powerbi) your youtube Analytics (beta) connector

<img width="533" alt="connect1" src="https://user-images.githubusercontent.com/2790375/83533301-b049ff80-a4ef-11ea-8d1d-349313b3fe7f.png">

<img width="560" alt="connect2" src="https://user-images.githubusercontent.com/2790375/83533465-e8514280-a4ef-11ea-82e0-3c1bf31e1352.png">

In google console I write the right redirection url
<img width="472" alt="google" src="https://user-images.githubusercontent.com/2790375/83533490-ee472380-a4ef-11ea-80dc-6221800fd3d2.PNG">

But I have the following message when I enter my gmail account (this is not a supported browser...)
<img width="357" alt="authentification-problem" src="https://user-images.githubusercontent.com/2790375/83533506-f2734100-a4ef-11ea-80cd-d912c1725e1a.PNG">

Thanks

**Comment by migueesc123** [comment]
Hey!
Unfortunately, I don't have any control over how the Webapp works or how it's being handled on a per account basis. This is something that might be related to your app being not a verified one as mentioned here:
https://support.google.com/cloud/answer/7454865?hl=en

Again, I don't control this part of the process as it's completely handled by Google so you might need to get in touch with them or your developer to set up your webapp. 
I can tell you that the Custom Connector is still working and it doesn't have any issues. Even the code used for the OAuth 2.0 in this repo is being used in other custom connectors on the web and it's working for other Google services such as Google Drive and more.

If you do happen to find out how to fix this issue or any way to bypass it, please let me know.

**Comment by noliverte** [comment]
Hello  migueesc123,

I used your link and advices but I always have the same problem with the pop-up security message in Powerbi...

I read a lot of information to fix this problem and asked to Google and Powerbi communities without good responses.

Your connector would be very usefull for me but I don't have any idea to fix this problem

Here's all what I did : 

- restart a test project in google console with a new gmail account
![tableau-de-bord](https://user-images.githubusercontent.com/2790375/83862678-92181580-a722-11ea-9c43-147a18d107ce.png)


- I fill input form in oauth autorisation screen as mentionned in your link
<img width="860" alt="ecran-auth2" src="https://user-images.githubusercontent.com/2790375/83863101-2aae9580-a723-11ea-88f7-2c09345b0197.png">


<img width="1097" alt="ecran-auth1" src="https://user-images.githubusercontent.com/2790375/83862966-f9ce6080-a722-11ea-934f-ab5c63d437c5.png">

- create an oauth 2.0 credential  with redirect URI
<img width="1097" alt="credential-web-application" src="https://user-images.githubusercontent.com/2790375/83863251-6184ab80-a723-11ea-9c54-0b3ad10e1d3f.png">
<img width="1422" alt="id-oauth2" src="https://user-images.githubusercontent.com/2790375/83863498-b4f6f980-a723-11ea-9044-918736d391ee.png">

- See a new entry in select form "desktop application"(compare with your video tutorial) 
<img width="557" alt="application-bureau" src="https://user-images.githubusercontent.com/2790375/83863625-e079e400-a723-11ea-84c2-4a1bb58357f2.png">

- I see a user with the same problem on the web
[https://support.google.com/accounts/thread/22475808?hl=en](https://support.google.com/accounts/thread/22475808?hl=en)

- Same problem with powerbi and google connexion since 2019
[https://community.powerbi.com/t5/Service/Cannot-sign-in-to-Google-Account-when-connecting-to-Google-Big/td-p/870032](url)

- I activated a less secure apps options
[https://support.google.com/accounts/answer/6010255](url)
[https://myaccount.google.com/lesssecureapps](url)

- import json file and rebuild new connector

 
Can you help me to fix this problem ?

Thanks

**Comment by migueesc123** [comment]
hey @noliverte 

My best suggestion would be to hire a developer to help you setup the Google Web App and debug any issues caused by the Authentication flow. I would've said that you could get in touch with my company to get support from us but, unfortunately, my developer is fully committed for the next few months and we don't have the bandwidth to take any support requests around new Web App configurations.

As mentioned before, I have zero control over how things work or are configured on the Google Web App - what I do have control over is on the Power BI Custom Connector code which you can see here:
https://github.com/migueesc123/YoutubeAnalytics/blob/YoutubeAnalyticsConnector/YoutubeAnalytics/YoutubeAnalytics.pq

The license of this repo does enable you to change the code of the connector as you see please should there be any changes needed to comply with the way that you've set up your Webapp.

Best of luck and if you find the fix, please share it with us!
