### ISSUE TITLE
YouTube Analytics Automated Refresh

### ISSUE THREAD

**Issue by aidaalibasic** [migueesc123/YoutubeAnalytics#41]
I successfully got the data pulled in from YouTube Analytics to Power BI. I got it published to Power BI Service and wanted the data to automatically refresh. I got an error "Power BI does not support YouTube Analytics automated refresh" when trying to set up automatic refresh in Power BI Service. Has anyone else had this issue, if so can you help me fix it? Thanks! 

![YouTube Analytics automated refresh](https://user-images.githubusercontent.com/54747851/84668630-7c0c1100-aee9-11ea-9167-50519d699fa7.png)

**Comment by migueesc123** [comment]
Hey!
This seems like there's no gateway configured for the dataset. 
This article might help you as the data gateway is a requirement for all Power BI Custom Connectors:
https://www.poweredsolutions.co/2018/04/23/refreshing-a-power-bi-custom-connector-in-the-cloud/
