### ISSUE TITLE
Video table Error, Access to the resource is forbidden

### ISSUE THREAD

**Issue by nafydnew** [migueesc123/YoutubeAnalytics#42]
Hi Miguel,

At one time the connection is all good but after I tried to edit the Youtube Analytics Template 'Top50Videos14Days' table's search pattern, I lost partial access to Youtube Analytics Data.

If I open an empty pbix file, connects to Youtube Analytics, **'Channel' and 'Countries' table still come in but 'Videos' table says Access to the resource is forbidden, any idea**?

the link to a screen shot is beloow
https://www.screencast.com/t/ILM0Utyal

**Comment by migueesc123** [comment]
Hey!
That's a tough one to diagnose. You'll need to trace your calls to the API and find out what response code you're getting from the API and why. If it's a 403 then this means that you lack some permissions on your web app and you'll need the add those or that it's missing some scopes.
Sadly, I haven't updated the template in years, so some things might not be working today like the "search".

I wish that I could tell you more, but all I can say that I'm unable to repro and this is working as intended in my environment.

**Comment by nafydnew** [comment]
much thanks! the problem is solved now, all tables are coming in and I didn't change anything.
