### ISSUE TITLE
Access to the resource is forbidden

### ISSUE THREAD

**Issue by steffels** [migueesc123/YoutubeAnalytics#43]
Hello! I am getting an error in Power Query: "Expression.Error: access to the resource is forbidden." This was working for me at the beginning of last month, I'm not sure what changed between then and now. If it seems like it's something on my end please let me know, I wanted to make sure I reported it here though. Thanks!

**Comment by migueesc123** [comment]
hey!
The "access to the resource is forbidden" is an error that you get when your token has expired or you don't have enough privileges to the data.
This is a response directly from the API and not something triggered by the custom connector itself, so this means that you'll need to do some troubleshooting to see why you're getting this error.
What you can try is to remove your data source credentials and try to log in again to see if that works. Maybe you have a really old access and refresh tokens and they expired, hence why you get this error.

Best!
