### ISSUE TITLE
Troubles with VideoStats

### ISSUE THREAD

**Issue by Formigs** [migueesc123/YoutubeAnalytics#46]
Hello Miguel!

In the Video Stats I noticed that when I set a start date of for example, 01/01/2010 and end date of 09/04/2021 I will get the data, but only after 26/02/2018.
It is only returning 100 videos when there should be at least 140 (considering the date-range I mencioned). 

If I set for example a start date of 01/01/2010 and an end-date of 25/02/2018 I will get the following error:

![image](https://user-images.githubusercontent.com/82189564/114115526-e2c84400-98da-11eb-826e-5f123bcef99a.png)

All the examples I provived had both false for country and partner.

I am trying to understand why it is happening but no luck :(.

Have you had this issue?

Thanks in advance,

**Comment by migueesc123** [comment]
Hey!
Sorry. I haven't had this issue before. The _comments_ error does appear to be pretty odd, but I'm unable to repro the issue on my end.

As you can imagine, there has been some interesting changes to the API over its long history so this might mean that some really old data might not be structured in the same way that the new data is.

Have you tried getting your data through the YouTube API Explorer or something like Postman to see what kind of responses you're getting? I'd start that way to get to the bottom of it and make any changes to the custom connector code as needed.

Unfortunately, there's not enough demand to adjust the code to this particular situation at the moment, but you can contact me at info@poweredsolutions.co if you'd like to us to check your particular situation through my remote consultancy channel.
