### ISSUE TITLE
Refresh in PowerBI Service | Sign in

### ISSUE THREAD

**Issue by Formigs** [migueesc123/YoutubeAnalytics#47]
Hi Miguel,

I am trying to do a refresh on the PowerBI service. I have the gateway installed and I have it detecting the connector, however, when I go to try to set the credentials in the Service it asks me to log in. I select the autenthication method Oauth2 and also choose the privacy level, afterwards it asks to trust and I say yes then it takes me to the Oauth 2.0 Playground. 

From there I am kinda stuck. What do I have to do here for it to log in in the PowerBI service? 
I've been trying to check around but no luck.

![image](https://user-images.githubusercontent.com/82189564/114531119-813e0780-9c43-11eb-8534-e93d5755afb0.png)

Thanks in advance,

**Comment by migueesc123** [comment]
Hey!
I'm not really familiar with this screen. I just did a test and couldn't repro.

Unfortunately these sort of situations are not so easy to reproduce as they might be quite specific to the setup that you have in your own application. 
You'll need to start debugging the calls that are being made during the FinishLogin phase of the OAuth 2.0 of the connector to see where you're being redirected and if perhaps the redirecturl has been properly set at your application level. That would be where I would start.

Hopefully it's as simple as checking if you missed adding the redirectUrl to your application. If not, a deeper investigation would be needed

Best of luck!

**Comment by Formigs** [comment]
Hello Miguel,

You are right, the issue was the RedirectUrl !

Thank you very much

Keep being awesome!
