### ISSUE TITLE
Credentials Problem

### ISSUE THREAD

**Issue by LeBossBeats** [migueesc123/YoutubeAnalytics#49]
Hi Miguel!

First of all, thanks for all the work for this.

I followed the steps multiple times but I always end with a message saying: _Connection can't be established. Delete your credentials and try again later._

The original message, in spanish is the following. Maybe it helps.

_No se puede establecer la conexión. Elimine sus credenciales e inténtelo de nuevo_

Can you help me with this?

Thanks!

**Comment by migueesc123** [comment]
Hola!

Thx for trying out the connector.

Unfortunately, this is a pretty generic error. It could be anything from:
- Your firewall
- Your network blocks some calls
- Your org has something in place that prevents you from using the API? (I've recently heard this is a thing in AAD, where you can select what users can do these sort of OAuth flows and for which applications)
- You entered the wrong credentials
- Your internet can't establish a connection to the REST API

The best that I can do is suggest to use something like Fiddler (or any other proxy) that will let you monitor what calls Power BI Desktop makes for the OAuth 2.0 process and see exactly what's the raw error message that you get from the REST API. This OAuth flow is something that we no control over. In other words, you can think of the connector as a "map" that tells Power BI Desktop what pathways to take inside your tenant "maze", but sometimes some tenants block some doors or completely get rid of some pathways and there are no workarounds (as they are part of the security layer).

I'm closing this one, but If you happen to get any other error messages please open a new issue.
