### ISSUE TITLE
Scheduled refresh in Service

### ISSUE THREAD

**Issue by fedetic** [migueesc123/YoutubeAnalytics#5]
Hi Miguel,

Thanks for posting this helpful report. However, is there any way of scheduling automatic data refreshes in Service? 

Hope to hear from you!

Joey

**Comment by migueesc123** [comment]
Hey Joey,

Hopefully soon there will be. You can find more information about the Custom Connectors Roadmap from Microsoft [here](https://github.com/microsoft/dataconnectors#coming-soon).

The workaround that people are doing nowadays is to use a 3rd party app like [Power Update](http://poweronbi.com/power-update/) to refresh their files programmatically and publish them to the service..
