### ISSUE TITLE
 Couldn’t sign you in

### ISSUE THREAD

**Issue by Nurzhan0220** [migueesc123/YoutubeAnalytics#54]
I work through a corporate network (VPN).
I did everything according to the instructions. But when I click to connect to the YoutubeAnalytics source, it requests authorization, when I try to log in, it gives the error "This browser or app may not be secure.

Try using a different browser. If you're already using a supported browser, you can try again to sign in."

Tried disabling VPN 
![image](https://user-images.githubusercontent.com/104829379/166435836-0309d8c4-d01d-4432-86db-fc921b444b11.png)
![image](https://user-images.githubusercontent.com/104829379/166435886-6547c6c6-19b2-4ed9-803a-b6c6b2c6881f.png)

**Comment by migueesc123** [comment]
Hey! 

Sorry for the late reply. This was a limitation of Power BI Desktop because it used a default Internet Explorer browser.

Please go to the Power BI Desktop settings and make sure that you have your local browser as the preferred way to authenticate.
