### ISSUE TITLE
Cannot fetch live streams

### ISSUE THREAD

**Issue by panrot** [migueesc123/YoutubeAnalytics#8]
Hi,
nice job!
I have a YouTube channel with live streams.
I want to fetch YouTube analytics (views, tracking time, average view duration, etc) of live streams (separately) into Bi Desktop with your repo. Now, this is impossible.
Can u help me pls?
Thank u!

**Comment by migueesc123** [comment]
Hey!

You could create your own query using the documentation found in the following [article](https://developers.google.com/youtube/reporting/v1/reports/dimensions#Playback_Location_Dimensions).

You'd need to use the "GET Reports" function inside the connector to make the API call, but it should be feasible.
